"""Add token revocation tracking and scope

Revision ID: 449c062c5de0
Revises: d9a4dcf19d99
Create Date: 2025-02-22 00:28:11.697873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449c062c5de0'
down_revision: Union[str, None] = 'd9a4dcf19d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tokens', sa.Column('revocation_reason', sa.Enum('logout', 'rotation', 'compromised', 'user_request', 'admin_request', name='revocationreason', create_constraint=True, length=20), nullable=True))
    op.add_column('tokens', sa.Column('scope', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'scope')
    op.drop_column('tokens', 'revocation_reason')
    op.drop_column('tokens', 'revoked_at')
    # ### end Alembic commands ###
