"""add pending email field

Revision ID: 62e2de016e80
Revises: ce512982da0c
Create Date: 2025-02-24 07:19:16.270358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e2de016e80'
down_revision: Union[str, None] = 'ce512982da0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_pending_email'), 'users', ['pending_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pending_email'), table_name='users')
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
