"""Initial migration

Revision ID: d9a4dcf19d99
Revises: 4d91b89d6859
Create Date: 2025-02-21 23:52:23.278710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a4dcf19d99'
down_revision: Union[str, None] = '4d91b89d6859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
