from typing import Any

class PostgresContainer:
    def __init__(self, image: str) -> None: ...
    def __enter__(self) -> PostgresContainer: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def get_connection_url(self) -> str: ...
