from typing import Any

class RedisContainer:
    def __init__(self, image: str) -> None: ...

    def __enter__(self) -> RedisContainer: ...

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

    def get_container_host_ip(self) -> str: ...

    def get_exposed_port(self, port: int) -> str: ...
